export const HERO_VIDEO  = '/videos/hero.mp4'
export const HERO_POSTER = '/images/hero/hero-poster.jpg'

export const COLLECTIONS = [
  { id: 'human-hair', title: 'Human Hair',  subtitle: 'Naturally sourced, silky & durable',  slug: 'human-hair',  count: 8,  coverImage: '/images/collections/human-hair.jpg' },
  { id: 'hd-lace',   title: 'HD Lace',     subtitle: 'Invisible hairline, flawless finish',  slug: 'hd-lace',     count: 2,  coverImage: null },
  { id: 'glueless',  title: 'Glueless',    subtitle: 'Install in minutes, no glue needed',   slug: 'glueless',    count: 2,  coverImage: null },
  { id: 'bob-wigs',  title: 'Bob Wigs',    subtitle: 'Short, chic & effortlessly sleek',     slug: 'bob-wigs',    count: 5,  coverImage: '/images/products/bob1-front.jpg' },
  { id: 'long-wigs', title: 'Long Wigs',   subtitle: 'Floor-length glamour & volume',        slug: 'long-wigs',   count: 3,  coverImage: '/images/products/long1-front.jpg' },
  { id: 'curly',     title: 'Curly Wigs',  subtitle: 'Defined curls with natural bounce',    slug: 'curly',       count: 5,  coverImage: '/images/products/curly1-front.jpg' },
  { id: 'body-wave', title: 'Body Wave',   subtitle: 'Soft S-shaped waves with movement',    slug: 'body-wave',   count: 6,  coverImage: null },
]

export const TEXTURES = [
  { id: 'straight',  label: 'Straight',  description: 'Sleek, smooth & polished',          coverImage: '/images/textures/straight.jpg?v=3'    },
  { id: 'body-wave', label: 'Body Wave', description: 'Soft S-shaped waves with movement', coverImage: '/images/textures/body-wave.jpg?v=3'   },
  { id: 'curly',     label: 'Curly',     description: 'Defined, bouncy curls',              coverImage: '/images/textures/kinky-coily.jpg?v=3' },
]

export const PRODUCTS = [

  // p1 — bob with bangs
  {
    _id: 'p1',
    name: 'Human Hair Closure Fringe Wig',
    slug: 'closure-fringe-wig',
    category: 'human-hair',
    texture: 'straight',
    price: 60000,
    comparePrice: null,
    rating: 4.8,
    reviewCount: 54,
    badge: null,
    description: '💯 Human hair closure fringe. 12 inches.',
    features: ['100% Human Hair', 'Closure Fringe', '12 Inches', 'Factory Made'],
    images: ['/images/products/p1-front.jpg?v=3', null, null, null],
    video: null,
    variants: { lengths: ['12"', '14"', '16"'], colors: ['Natural Black'] },
    inStock: true, isNew: false, isBestSeller: false,
  },

  // hd1 — video 102 — Natural Colour HD Lace
  {
    _id: 'hd1',
    name: '5x5 HD Lace One Donor DD Bounce Wig',
    slug: 'hd-lace-dd-bounce-natural',
    category: 'hd-lace',
    texture: 'body-wave',
    price: 180000,
    comparePrice: null,
    rating: 5.0,
    reviewCount: 14,
    badge: 'Premium',
    description: '5x5 HD LACE ONE DONOR DD Bounce Natural Colour. 100% human hair factory made. 14 inch — ₦180,000.',
    features: ['100% Human Hair', '5x5 HD Lace', 'One Donor Hair', 'DD Bounce', 'Natural Colour', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/hd-lace-102.mp4',
    variants: { lengths: ['14"'], colors: ['Natural Colour'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // hd2 — video 101 — Two Tone Colour HD Lace
  {
    _id: 'hd2',
    name: '5x5 HD Lace One Donor DD Bounce Two Tone Wig',
    slug: 'hd-lace-dd-bounce-two-tone',
    category: 'hd-lace',
    texture: 'body-wave',
    price: 185000,
    comparePrice: null,
    rating: 5.0,
    reviewCount: 9,
    badge: 'Premium',
    description: '5x5 HD LACE ONE DONOR DD Bounce Two Tone Colour. 100% human hair factory made. Price: ₦185,000.',
    features: ['100% Human Hair', '5x5 HD Lace', 'One Donor Hair', 'DD Bounce', 'Two Tone Colour', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/hd-lace-101.mp4',
    variants: { lengths: ['14"', '16"'], colors: ['Two Tone Colour'] },
    inStock: true, isNew: true, isBestSeller: true,
  },  // p2 — big curly afro
  {
    _id: 'p2',
    name: 'Omotola Fridge Bounce Wig',
    slug: 'omotola-fridge-bounce',
    category: 'human-hair',
    texture: 'curly',
    price: 55000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 112,
    badge: 'Best Seller',
    description: 'Omotola fridge bounce. 💯 Human hair factory made.',
    features: ['100% Human Hair', 'Factory Made', 'Fridge Bounce Texture', 'Natural Hairline'],
    images: ['/images/products/p2-front.jpg?v=3', null, null, null],
    video: null,
    variants: { lengths: ['14"', '16"', '18"', '20"'], colors: ['Natural Black'] },
    inStock: true, isNew: false, isBestSeller: true,
  },

  // p3 — pixie curly bob collage
  {
    _id: 'p3',
    name: 'Jessy Full Frontal Wig',
    slug: 'jessy-full-frontal',
    category: 'human-hair',
    texture: 'curly',
    price: 40000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 87,
    badge: 'Best Seller',
    description: 'Jessy full frontal. 💯 Human hair. Brown colour is also available.',
    features: ['100% Human Hair', 'Full Frontal', 'Natural Black & Brown available', 'Factory Made'],
    images: ['/images/products/p3-front.jpg?v=3', null, null, null],
    video: null,
    variants: { lengths: ['12"', '14"', '16"', '18"', '20"'], colors: ['Natural Black', 'Brown'] },
    inStock: true, isNew: false, isBestSeller: true,
  },

  // p4 — long body wave red lips
  {
    _id: 'p4',
    name: 'Full Frontal Human Hair Body Blend Wig',
    slug: 'full-frontal-body-blend',
    category: 'human-hair',
    texture: 'body-wave',
    price: 52000,
    comparePrice: null,
    rating: 4.8,
    reviewCount: 61,
    badge: 'New',
    description: 'Full frontal 💯 human hair paired with body blend.',
    features: ['100% Human Hair', 'Full Frontal', 'Body Blend', 'Natural Hairline', 'Factory Made'],
    images: ['/images/products/p4-front.jpg?v=3', null, null, null],
    video: null,
    variants: { lengths: ['14"', '16"', '18"', '20"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: false,
  },

  // p5 — brown curly dark background
  {
    _id: 'p5',
    name: 'Pixi Curls Two Tone T-Closure Wig',
    slug: 'pixi-curls-two-tone',
    category: 'human-hair',
    texture: 'curly',
    price: 40000,
    comparePrice: null,
    rating: 4.7,
    reviewCount: 38,
    badge: null,
    description: 'Affordable human hair pixi curls two tone T closure wig.',
    features: ['Human Hair', 'Two Tone Colour', 'T-Closure', 'Pixi Curl Pattern'],
    images: ['/images/products/p5-front.jpg?v=3', null, null, null],
    video: null,
    variants: { lengths: ['8"', '10"', '12"'], colors: ['Two Tone (Black & Brown)'] },
    inStock: true, isNew: false, isBestSeller: false,
  },

  // p6 ★ SPOTLIGHT ★ — short curly earrings floral top
  {
    _id: 'p6',
    name: 'Caribbean Curls Closure Wig',
    slug: 'caribbean-curls-closure',
    category: 'human-hair',
    texture: 'curly',
    price: 40000,
    comparePrice: null,
    rating: 4.8,
    reviewCount: 67,
    badge: 'New',
    description: 'Closure human hair blend CARIBBEAN CURLS. Very soft texture.',
    features: ['Human Hair Blend', 'Caribbean Curl Pattern', 'Very Soft Texture', 'Closure'],
    images: ['/images/products/p6-front.jpg?v=3', null, null, null],
    video: '/videos/spotlight.mp4',
    variants: { lengths: ['12"', '14"', '16"', '18"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: false,
  },

  // p7 — deep wave curls mannequin (Burmese)
  {
    _id: 'p7',
    name: 'Burmese Curl 5x5 Closure Wig',
    slug: 'burmese-curl-5x5',
    category: 'human-hair',
    texture: 'curly',
    price: 120000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 21,
    badge: 'Premium',
    description: '💯 Human hair 5x5 Burmese curl. Factory made. 14" — ₦120,000 | 16" — ₦135,000',
    features: ['100% Human Hair', '5x5 Closure', 'Burmese Curl', 'Factory Made', '14" ₦120k | 16" ₦135k'],
    images: ['/images/products/p9-front.jpg?v=3', null, null, null],
    video: null,
    variants: { lengths: ['14"', '16"'], colors: ['Natural Black'] },
    inStock: true, isNew: false, isBestSeller: true,
  },

  // p8 — long bone straight (STW)
  {
    _id: 'p8',
    name: 'Human Hair Full Closure STW Wig',
    slug: 'full-closure-stw-24',
    category: 'human-hair',
    texture: 'straight',
    price: 115000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 33,
    badge: 'Premium',
    description: '💯 Human hair full closure stw. 24" factory made.',
    features: ['100% Human Hair', 'Full Closure', '24 Inches', 'Factory Made', 'Bone Straight'],
    images: ['/images/products/p8-front.jpg?v=3', null, null, null],
    video: null,
    variants: { lengths: ['20"', '22"', '24"', '26"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // gl1 — video 103 — Glueless Highlight Cajun Colour
  {
    _id: 'gl1',
    name: '5x5 HD Glueless Closure Wavy Wig – Cajun Highlight',
    slug: 'hd-glueless-wavy-cajun',
    category: 'glueless',
    texture: 'body-wave',
    price: 78000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 17,
    badge: 'New',
    description: '5x5 HD Glueless Closure Wavy. Finest premium Futura quality, factory made. Available in Highlight Cajun Colour. Accepts low heat and oil serum for easy maintenance. Glueless as seen in live video.',
    features: ['5x5 HD Closure', 'Glueless', 'Futura Quality', 'Highlight Cajun Colour', 'Low Heat Friendly', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/glueless-103.mp4',
    variants: { lengths: ['14"', '16"', '18"'], colors: ['Highlight Cajun'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // gl2 — video 104 — Glueless Highlight Gold Colour
  {
    _id: 'gl2',
    name: 'Soft Layered 5x5 HD Glueless Closure Wavy Wig – Gold Highlight',
    slug: 'hd-glueless-wavy-gold',
    category: 'glueless',
    texture: 'body-wave',
    price: 78000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 12,
    badge: 'New',
    description: 'Soft Layered 5x5 HD Glueless Closure Wavy. Finest premium Futura quality, factory made. Available in Highlight Gold Colour. Accepts low heat and oil serum for easy maintenance. Glueless as seen in live video.',
    features: ['5x5 HD Closure', 'Glueless', 'Soft Layered', 'Futura Quality', 'Highlight Gold Colour', 'Low Heat Friendly', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/glueless-104.mp4',
    variants: { lengths: ['14"', '16"', '18"'], colors: ['Highlight Gold'] },
    inStock: true, isNew: true, isBestSeller: false,
  },

  // bob1 — photo: blonde bob 4/613
  {
    _id: 'bob1',
    name: 'DD Full Frontal Bob Wig – 4/613',
    slug: 'dd-full-frontal-bob-4-613',
    category: 'bob-wigs',
    texture: 'straight',
    price: 75000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 22,
    badge: 'Premium',
    description: '(DD) Full Frontal Bob — 4/613#. 💯 Human hair factory made. Stunning two-tone colour.',
    features: ['100% Human Hair', 'Full Frontal', '4/613 Colour', 'DD Bob', 'Factory Made'],
    images: ['/images/products/bob1-front.jpg', null, null, null],
    video: null,
    variants: { lengths: ['10"', '12"', '14"'], colors: ['4/613 (Dark Root / Blonde)'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // bob2 — photo: multiple bobs, model with pink top
  {
    _id: 'bob2',
    name: 'Human Hair 4x4 Closure Bob Wig',
    slug: 'human-hair-4x4-closure-bob',
    category: 'bob-wigs',
    texture: 'straight',
    price: 48000,
    comparePrice: null,
    rating: 4.8,
    reviewCount: 43,
    badge: 'Best Seller',
    description: '💯 Human hair factory made bob wig with 4 by 4 closure. Sleek and natural looking.',
    features: ['100% Human Hair', '4x4 Closure', 'Factory Made', 'Natural Black'],
    images: ['/images/products/bob2-front.jpg', null, null, null],
    video: null,
    variants: { lengths: ['10"', '12"', '14"'], colors: ['Natural Black'] },
    inStock: true, isNew: false, isBestSeller: true,
  },

  // bob3 — photo: 4x4 bob collage
  {
    _id: 'bob3',
    name: 'Hh2x4 Student Bob Wig',
    slug: 'hh2x4-student-bob',
    category: 'bob-wigs',
    texture: 'straight',
    price: 40000,
    comparePrice: null,
    rating: 4.7,
    reviewCount: 31,
    badge: null,
    description: '💯 Hh2 by 4 student bob. Factory made. Affordable and natural looking.',
    features: ['100% Human Hair', '2x4 Closure', 'Student Bob', 'Factory Made'],
    images: ['/images/products/bob3-front.jpg', null, null, null],
    video: null,
    variants: { lengths: ['10"', '12"'], colors: ['Natural Black'] },
    inStock: true, isNew: false, isBestSeller: false,
  },

  // bob4 — video 105 — SDD Bob 5x5
  {
    _id: 'bob4',
    name: 'Human Hair 5x5 SDD Bob Wig',
    slug: 'human-hair-5x5-sdd-bob',
    category: 'bob-wigs',
    texture: 'straight',
    price: 75000,
    comparePrice: null,
    rating: 5.0,
    reviewCount: 18,
    badge: 'Premium',
    description: 'Human hair 5 by 5 SDD Bob factory made.\n\n10" — ₦75,000\n12" — ₦85,000',
    features: ['100% Human Hair', '5x5 Closure', 'SDD Bob', 'Factory Made', '10" ₦75k | 12" ₦85k'],
    images: [null, null, null, null],
    video: '/videos/bob-105.mp4',
    variants: { lengths: ['10"', '12"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // bob5 — video 106 — SDD 5x5 Colour 99j
  {
    _id: 'bob5',
    name: 'SDD 5x5 Bob Wig – Colour 99J',
    slug: 'sdd-5x5-bob-99j',
    category: 'bob-wigs',
    texture: 'straight',
    price: 86000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 11,
    badge: 'New',
    description: 'SDD 5x5 Colour 99J. Rich burgundy colour with a stunning bob cut.',
    features: ['100% Human Hair', '5x5 Closure', 'SDD Bob', 'Colour 99J', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/bob-106.mp4',
    variants: { lengths: ['10"', '12"'], colors: ['99J (Burgundy)'] },
    inStock: true, isNew: true, isBestSeller: false,
  },

  // long1 — photo: blonde 34" STW blend
  {
    _id: 'long1',
    name: 'STW Blend 5x5 Closure Wig – Colour 613',
    slug: 'stw-blend-5x5-colour-613',
    category: 'long-wigs',
    texture: 'straight',
    price: 60500,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 19,
    badge: 'Premium',
    description: 'STW BLEND 5x5 CLOSURE. Factory made. Colour 613. 34 inches of jaw-dropping straight hair.',
    features: ['STW Blend', '5x5 Closure', 'Factory Made', 'Colour 613', '34 Inches'],
    images: ['/images/products/long1-front.jpg', null, null, null],
    video: null,
    variants: { lengths: ['34"'], colors: ['613 (Blonde)'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // long2 — video 107 — Virgin Unprocessed SDD Straight Extra Length
  {
    _id: 'long2',
    name: 'Virgin Unprocessed SDD Straight Wig 38"–40"',
    slug: 'virgin-unprocessed-sdd-straight-38-40',
    category: 'long-wigs',
    texture: 'straight',
    price: 450000,
    comparePrice: null,
    rating: 5.0,
    reviewCount: 7,
    badge: 'Premium',
    description: 'NEW IN — Virgin Unprocessed SDD Straight. Available in 5x5 and 13x4 Swiss Transparent Lace. 100% human hair factory made. 346grm. Extra Length 38"–40". Can be dyed to any colour. Produced in India — not Chinese or Vietnam.',
    features: ['Virgin Unprocessed', '5x5 & 13x4 Swiss Lace', '100% Human Hair', '346grm', 'Extra Length 38"–40"', 'Can Be Dyed', 'Made in India'],
    images: [null, null, null, null],
    video: '/videos/long-107.mp4',
    variants: { lengths: ['38"', '40"'], colors: ['Natural (Unprocessed — can be dyed)'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // long3 — video 108 — SDD Vietnamese Bone Straight Bundles
  {
    _id: 'long3',
    name: 'SDD Vietnamese Bone Straight Bundles + 2x6 Closure',
    slug: 'sdd-vietnamese-bone-straight-bundles',
    category: 'long-wigs',
    texture: 'straight',
    price: 215000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 11,
    badge: 'New',
    description: 'SDD Vietnamese bone straight. 200g bundles + 2x6 closure.\n\n18 inches — ₦215,000\n20 inches — ₦235,000',
    features: ['SDD Vietnamese Hair', '200g Bundles', '2x6 Closure', 'Bone Straight', '18" ₦215k | 20" ₦235k'],
    images: [null, null, null, null],
    video: '/videos/long-108.mp4',
    variants: { lengths: ['18"', '20"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: false,
  },

  // curly1 — photo: black curly SDD 5x5 natural
  {
    _id: 'curly1',
    name: 'SDD 5x5 Pixies Curly Wig – Natural Colour',
    slug: 'sdd-5x5-pixies-curly-natural',
    category: 'curly',
    texture: 'curly',
    price: 140000,
    comparePrice: null,
    rating: 5.0,
    reviewCount: 16,
    badge: 'Premium',
    description: 'SDD 5x5 Pixies Curly Natural Colour. 💯 Factory made. 18 inches — ₦140,000.',
    features: ['100% Human Hair', 'SDD', '5x5 Closure', 'Pixies Curly', 'Natural Colour', 'Factory Made'],
    images: ['/images/products/curly1-front.jpg', null, null, null],
    video: null,
    variants: { lengths: ['18"'], colors: ['Natural Colour'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // curly2 — photo: burgundy/99j curly SDD 5x5
  {
    _id: 'curly2',
    name: 'SDD 5x5 Pixies Curly Wig – 99J Colour',
    slug: 'sdd-5x5-pixies-curly-99j',
    category: 'curly',
    texture: 'curly',
    price: 140000,
    comparePrice: null,
    rating: 5.0,
    reviewCount: 12,
    badge: 'Premium',
    description: 'SDD 5x5 Pixies Curly 99J. 💯 Factory made. 18 inches — ₦140,000. Rich burgundy colour.',
    features: ['100% Human Hair', 'SDD', '5x5 Closure', 'Pixies Curly', '99J Colour', 'Factory Made'],
    images: ['/images/products/curly2-front.jpg', null, null, null],
    video: null,
    variants: { lengths: ['18"'], colors: ['99J (Burgundy)'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // curly3 — photo: 4x4 deep/JC natural 26"
  {
    _id: 'curly3',
    name: '4x4 Deep/JC Natural Colour Wig',
    slug: '4x4-deep-jc-natural-26',
    category: 'curly',
    texture: 'curly',
    price: 125000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 8,
    badge: 'Premium',
    description: '4x4 Deep/JC Natural Color. 💯 Human hair. Factory made. 26 inches — ₦125,000.',
    features: ['100% Human Hair', '4x4 Closure', 'Deep/JC Curl', 'Natural Colour', '26 Inches', 'Factory Made'],
    images: ['/images/products/curly3-front.jpg', null, null, null],
    video: null,
    variants: { lengths: ['26"'], colors: ['Natural Colour'] },
    inStock: true, isNew: true, isBestSeller: false,
  },

  // curly4 — video 109 — 4x4 closure jerry curl
  {
    _id: 'curly4',
    name: '4x4 Closure Jerry Curl Wig',
    slug: '4x4-closure-jerry-curl',
    category: 'curly',
    texture: 'curly',
    price: 70000,
    comparePrice: null,
    rating: 4.8,
    reviewCount: 23,
    badge: 'New',
    description: '4x4 closure jerry curl. 💯 Human hair.\n\n12 inches — ₦70,000\n14 inches — ₦75,000\n16 inches — ₦85,000',
    features: ['100% Human Hair', '4x4 Closure', 'Jerry Curl', '12" ₦70k | 14" ₦75k | 16" ₦85k'],
    images: [null, null, null, null],
    video: '/videos/curly-109.mp4',
    variants: { lengths: ['12"', '14"', '16"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: false,
  },

  // curly5 — video 110 — Human hair bouncy curls
  {
    _id: 'curly5',
    name: 'Human Hair Bouncy Curls Wig',
    slug: 'human-hair-bouncy-curls',
    category: 'curly',
    texture: 'curly',
    price: 55000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 31,
    badge: 'New',
    description: 'Human hair bouncy curls. Exactly as seen. Price: ₦55,000.',
    features: ['Human Hair', 'Bouncy Curls', 'Natural Look', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/curly-110.mp4',
    variants: { lengths: ['14"', '16"', '18"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: false,
  },

  // ── BODY WAVE collection ─────────────────────────────────

  // bw1 — video 111 — SDD 5x5 Layer Bounce Natural
  {
    _id: 'bw1',
    name: 'SDD 5x5 Layer Bounce Wig – Natural Colour',
    slug: 'sdd-5x5-layer-bounce-natural',
    category: 'body-wave',
    texture: 'body-wave',
    price: 160000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 14,
    badge: 'New',
    description: 'SDD 5x5 Layer Bounce. Factory made. 💯 Human hair factory made. Natural colour. 20 inches — ₦160,000. All colours available.',
    features: ['100% Human Hair', '5x5 Closure', 'SDD Layer Bounce', 'Natural Colour', 'All Colours Available', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/bodywave-111.mp4',
    variants: { lengths: ['20"'], colors: ['Natural Colour', 'All Colours Available'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // bw2 — video 112 — 5x5 Piano Bounce 24"
  {
    _id: 'bw2',
    name: '5x5 Piano Bounce Wig',
    slug: '5x5-piano-bounce-24',
    category: 'body-wave',
    texture: 'body-wave',
    price: 237000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 9,
    badge: 'Premium',
    description: '5x5 Piano Bounce. 24 inches — ₦237,000.',
    features: ['5x5 Closure', 'Piano Bounce', '24 Inches', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/bodywave-112.mp4',
    variants: { lengths: ['24"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // bw3 — video 113 wig 1 — SDD Tiwa Wig 5x5
  {
    _id: 'bw3',
    name: 'SDD Tiwa Wig 5x5 Closure',
    slug: 'sdd-tiwa-wig-5x5',
    category: 'body-wave',
    texture: 'body-wave',
    price: 75000,
    comparePrice: null,
    rating: 4.8,
    reviewCount: 22,
    badge: 'Best Seller',
    description: 'SDD Tiwa wig 5x5 closure. 💯 Human hair. Price: ₦75,000.',
    features: ['100% Human Hair', '5x5 Closure', 'SDD Tiwa Style', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/bodywave-113.mp4',
    variants: { lengths: ['14"', '16"', '18"', '20"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // bw4 — video 113 wig 2 — 4x4 Closure Flip Bounce
  {
    _id: 'bw4',
    name: 'Human Hair 4x4 Closure Flip Bounce Wig',
    slug: 'human-hair-4x4-flip-bounce',
    category: 'body-wave',
    texture: 'body-wave',
    price: 75000,
    comparePrice: null,
    rating: 4.8,
    reviewCount: 18,
    badge: null,
    description: '💯 Human hair 4x4 closure flip bounce. Price: ₦75,000.',
    features: ['100% Human Hair', '4x4 Closure', 'Flip Bounce', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/bodywave-113.mp4',
    variants: { lengths: ['14"', '16"', '18"', '20"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: false,
  },

  // bw5 — video 114 — 5x5 HD Flip Bounce Natural
  {
    _id: 'bw5',
    name: '5x5 HD Flip Bounce Wig – Natural',
    slug: '5x5-hd-flip-bounce-natural',
    category: 'body-wave',
    texture: 'body-wave',
    price: 155000,
    comparePrice: null,
    rating: 5.0,
    reviewCount: 11,
    badge: 'Premium',
    description: '5x5 HD Flip Bounce. Natural colour — ₦155,000. Sky fashion 💜',
    features: ['5x5 HD Closure', 'Flip Bounce', 'Natural Colour', 'Sky Fashion', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/bodywave-114.mp4',
    variants: { lengths: ['18"', '20"', '22"'], colors: ['Natural Colour'] },
    inStock: true, isNew: true, isBestSeller: true,
  },

  // bw6 — video 115 — 5x5 SDD Bounce Piano 14"
  {
    _id: 'bw6',
    name: '5x5 SDD Bounce Piano Wig',
    slug: '5x5-sdd-bounce-piano-14',
    category: 'body-wave',
    texture: 'body-wave',
    price: 175000,
    comparePrice: null,
    rating: 4.9,
    reviewCount: 7,
    badge: 'New',
    description: '5x5 SDD Bounce Piano. 14 inches — ₦175,000.',
    features: ['5x5 Closure', 'SDD Bounce Piano', '14 Inches', 'Factory Made'],
    images: [null, null, null, null],
    video: '/videos/bodywave-115.mp4',
    variants: { lengths: ['14"'], colors: ['Natural Black'] },
    inStock: true, isNew: true, isBestSeller: false,
  },

]

export const REVIEWS = [
  { id: 'r1', name: 'Adaeze M.',   location: 'Lagos',         rating: 5, text: "JustHairs is on a different level. The lace is literally undetectable. Everyone thinks it's my real hair!",       image: '/images/customers/review1.jpg', product: 'Human Hair Closure Fringe Wig', date: '2024-08-12' },
  { id: 'r2', name: 'Chisom K.',   location: 'Abuja',         rating: 5, text: 'The Caribbean Curls wig is so soft and bouncy. I get compliments every single day. Already ordered a second one!', image: '/images/customers/review2.jpg', product: 'Caribbean Curls Closure Wig',   date: '2024-09-01' },
  { id: 'r3', name: 'Blessing O.', location: 'Port Harcourt', rating: 5, text: 'Quality is unmatched. The Omotola Bounce wig is everything. So natural. Already recommended to all my friends!',  image: '/images/customers/review3.jpg', product: 'Omotola Fridge Bounce Wig',     date: '2024-09-05' },
  { id: 'r4', name: 'Temi A.',     location: 'Lagos',         rating: 5, text: 'Ordered the Burmese Curl and I get compliments everywhere I go. The curls are defined and the lace so natural.',   image: '/images/customers/review4.jpg', product: 'Burmese Curl 5x5 Closure Wig', date: '2024-08-20' },
]

export const BEST_SELLERS      = PRODUCTS.filter(p => p.isBestSeller)
export const NEW_ARRIVALS      = PRODUCTS.filter(p => p.isNew)
export const SPOTLIGHT_PRODUCT = PRODUCTS.find(p => p._id === 'p6')
